### PR TITLE
Bump ruamel version

### PR DESCRIPTION
**Pull request by mithun**
* This is required to support python3.7
*  https://bitbucket.org/ruamel/yaml/issues/187/python-37-beta-incompatibility

### CODE REVIEW

**Comment by chfw** [comment]
Heads up. This is what I am having:

```
$ pip install yamlfmt
Collecting yamlfmt
  Using cached https://files.pythonhosted.org/packages/3a/c5/53e1f03bc752a66c48ca12e86b36e3f079fc7e2d96113927dac667ad392c/yamlfmt-1.0.0-py2.py3-none-any.whl
Collecting ruamel.yaml<0.15 (from yamlfmt)
  Using cached https://files.pythonhosted.org/packages/cf/86/7ef6c24317e20e6cef0eab407520d49f3d3836e454d5377bdcbcf03d385c/ruamel.yaml-0.14.12.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/gw/gnxg0qxd2ll0qlrhkx_t2n8h0000gn/T/tmp_ruamel__bel23fh/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/gw/gnxg0qxd2ll0qlrhkx_t2n8h0000gn/T/tmp_ruamel__bel23fh/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/gw/gnxg0qxd2ll0qlrhkx_t2n8h0000gn/T/tmp_ruamel__bel23fh/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gw/gnxg0qxd2ll0qlrhkx_t2n8h0000gn/T/pip-install-j_iprudp/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/var/folders/gw/gnxg0qxd2ll0qlrhkx_t2n8h0000gn/T/pip-install-j_iprudp/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/setuptools/dist.py", line 442, in __init__
        k: v for k, v in attrs.items()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

```

**Comment by thinkl33t** [comment]
I can confirm this makes yamlfmt work again on 3.7 on Debian Buster

**Comment by irvingpop** [comment]
Please merge @mmlb this totally fixes things for Python 3.7:

```
$ pip3 install git+https://github.com/mmlb/yamlfmt.git@refs/pull/9/head
Collecting git+https://github.com/mmlb/yamlfmt.git@refs/pull/9/head
  Cloning https://github.com/mmlb/yamlfmt.git (to revision refs/pull/9/head) to /private/var/folders/_p/4gbvlmcs3tq47vsh14_4bfz80000gn/T/pip-req-build-dd25qq5g
  Running command git clone -q https://github.com/mmlb/yamlfmt.git /private/var/folders/_p/4gbvlmcs3tq47vsh14_4bfz80000gn/T/pip-req-build-dd25qq5g
  WARNING: Did not find branch or tag 'refs/pull/9/head', assuming revision or ref.
  Running command git fetch -q https://github.com/mmlb/yamlfmt.git refs/pull/9/head
  Running command git checkout -q cd49152a514621c67edcdfa1890b79af248945b5
Collecting ruamel.yaml<0.16 (from yamlfmt==1.0.0)
  Downloading https://files.pythonhosted.org/packages/a6/e0/e65db3b59ad417113b50040bd083e489309343f7653f4ce75ec52518ad56/ruamel.yaml-0.15.100-cp37-cp37m-macosx_10_9_x86_64.whl (254kB)
     |████████████████████████████████| 256kB 2.1MB/s
Building wheels for collected packages: yamlfmt
  Building wheel for yamlfmt (setup.py) ... done
  Stored in directory: /private/var/folders/_p/4gbvlmcs3tq47vsh14_4bfz80000gn/T/pip-ephem-wheel-cache-ba24up7q/wheels/02/66/e3/98e7e528dcadf83204cc29c1f2ca20da82d1caa67ba37beb9a
Successfully built yamlfmt
Installing collected packages: ruamel.yaml, yamlfmt
Successfully installed ruamel.yaml-0.15.100 yamlfmt-1.0.0
```

**Comment by petski** [comment]
`$ docker run --rm -i python:3.8-slim sh -c 'pip install yamlfmt'` ❌
`$ docker run --rm -i python:3.7-slim sh -c 'pip install yamlfmt'` ❌
`$ docker run --rm -i python:3.6-slim sh -c 'pip install yamlfmt'` ✔

Version bump should fix this, see https://bitbucket.org/ruamel/yaml/issues/261/error-while-installing-ruamelyaml-setuppy for details.

**Comment by mmlb** [comment]
Will merge, there was a reason for the pin to said version I think due to incompatibilities. That said if it works for you all then sgtm. Sorry for letting this sit around.

**Pull request merged**
